apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: yo
spec:
# node를 통해 직접 접근 가능한 타입
  type: NodePort
  ports:
  - port: 80   #service 포트
    targetPort: 80    #service가 routing해줄 대상 port (pod)
    nodePort: 30100
# pod의 labels.app과 service의 seletor.app이 일치해야함
  selector:
    app: my-nginx
