apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: yo
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: yo
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: yo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  selector:
    app: my-nginx